export const GET_CHAMPIONS_REQUEST = "GET_CHAMPIONS_REQUEST";
export const GET_CHAMPIONS_SUCCESS = "GET_CHAMPIONS_SUCCESS";
export const GET_CHAMPIONS_FAIL = "GET_CHAMPIONS_FAIL";
export const ADD_MOVIE_TO_WATCHLIST = "ADD_MOVIE_TO_WATCHLIST";
export const REMOVE_MOVIE_FROM_WATCHLIST = "REMOVE_MOVIE_FROM_WATCHLIST";
